# Add configuration values here, as shown below.
#
# pusher_app_id: "2954"
# pusher_key: 7381a978f7dd7f9a1117
# pusher_secret: abdc3b896a0ffb85d373
# stripe_api_key: sk_test_2J0l093xOyW72XUYJHE4Dv2r
# stripe_publishable_key: pk_test_ro9jV5SNwGb1yYlQfzG17LHK
#
# production:
#   stripe_api_key: sk_live_EeHnL644i6zo4Iyq4v1KdV9H
#   stripe_publishable_key: pk_live_9lcthxpSIHbGwmdO941O1XVU
AWS_ACCES_KEY_ID: AKIAI4EVN2DZVX2PKGVA
AWS_SECRET_ACCESS_KEY: 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
EMAIL_LOGIN: pablingonzales@gmail.com
EMAIL_PASSWORD: pablin236213
AWS_REGION: us-east-1
development:
  S3_BUCKET_NAME: revista-dev
production:
  S3_BUCKET_NAME: revista-production
